export const LOAD_TASKS = 'LOAD_TASKS';
export const LOAD_TASKS_RESPONSE = 'LOAD_TASKS_RESPONSE';
export const ADD_TASK = 'ADD_TASK';
export const TOGGLE_TASK = 'TOGGLE_TASK';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';